# Generated by Django 4.2.17 on 2024-12-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student', max_length=255)),
                ('age', models.IntegerField(blank=True, help_text='Age of the student', null=True)),
                ('class_name', models.CharField(blank=True, help_text='Class or grade the student is in', max_length=50, null=True)),
                ('roll_number', models.CharField(blank=True, help_text='Unique roll number of the student', max_length=50, null=True, unique=True)),
                ('guardian_name', models.CharField(blank=True, help_text="Name of the student's guardian", max_length=255, null=True)),
                ('guardian_contact', models.CharField(blank=True, help_text='Contact number of the guardian', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text='Residential address of the student', null=True)),
                ('date_of_admission', models.DateField(blank=True, help_text='Date when the student was admitted', null=True)),
                ('section', models.CharField(blank=True, help_text='Section of the class, e.g., A, B, C', max_length=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], default='active', help_text='Current status of the student', max_length=50)),
            ],
        ),
    ]
