# Generated by Django 4.2.17 on 2024-12-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
